version: '3.7'

services:
  nifi-cli:
    container_name: nifi_oidc_toolkit_cli
    image: apache/nifi-toolkit:${NIFI_VERSION-1.15.2}
    hostname: localhost
    environment:
      NIFI_REGISTRY_BASE_URL: https://localhost:18443
      KEYSTORE_PATH: /opt/certs/keystore.jks
      KEYSTORE_TYPE: JKS
      KEYSTORE_PASSWORD: DWz5dsLUG0ig9KHVRT/peR1ObBvchcL6HEOXRRPv+Zs
      TRUSTSTORE_PATH: /opt/certs/truststore.jks
      TRUSTSTORE_TYPE: JKS
      TRUSTSTORE_PASSWORD: qgWe9cn6Mn4fKAA+CtGAkzseZzaK2/ywBmN1ZSOiesE
      NIFI_REGISTRY_PROXIED_IDENTITY: user@example.com
    entrypoint: [ "/opt/nifi-toolkit/oidc_scripts/nifi-cli.sh" ]
    volumes:
      - ./nifi/certs:/opt/certs
      - ./nifi/scripts/:/opt/nifi-toolkit/oidc_scripts
    depends_on:
      - nifi
      - nifi-registry
    network_mode: host
